#!/bin/bash

SOCKS_PORT=2080
TUN2SOCKS_BIN="/usr/local/bin/tun2socks"

SCRIPT_PATH="$(realpath "$0")"

if [ "$EUID" -ne 0 ]; then
  exec sudo \
    __DISP="$DISPLAY" \
    __WAY="$WAYLAND_DISPLAY" \
    __XAUTH="$XAUTHORITY" \
    __XDG="$XDG_RUNTIME_DIR" \
    __DBUS="$DBUS_SESSION_BUS_ADDRESS" \
    "$SCRIPT_PATH" "$@"
  exit $?
fi

REAL_USER=${SUDO_USER}

while true; do
  ID=$(tr -dc 'a-z0-9' < /dev/urandom | head -c 8)
  NS="ns_${ID}"
  VETH_HOST="vh_${ID}"
  if ! ip netns show | grep -qw "$NS"; then
    break
  fi
done

while true; do
  SUBNET1=$(( (RANDOM % 240) + 10 ))
  SUBNET2=$(( (RANDOM % 240) + 10 ))
  HOST_IP="10.${SUBNET1}.${SUBNET2}.1"
  NS_IP="10.${SUBNET1}.${SUBNET2}.2"
  if ! ip route show | grep -q "10.${SUBNET1}.${SUBNET2}.0/24"; then
    break
  fi
done

if [ -z "$1" ]; then
    >&2 echo "Usage: proxy-nns <command>"
    exit 1
else
  CMD=("$@")
fi

cleanup() {
  echo "Cleaning up [ $NS ]..."
  kill $TUN_PID 2>/dev/null
  if command -v firewall-cmd >/dev/null 2>&1; then
    firewall-cmd --zone=trusted --remove-interface=$VETH_HOST > /dev/null 2>&1
  fi
  ip netns del $NS 2>/dev/null
}
trap cleanup EXIT

echo "[1] Configuring network namespace and virtual network..."
ip netns del $NS 2>/dev/null
ip netns add $NS
ip link add $VETH_HOST type veth peer name veth_ns
ip link set veth_ns netns $NS

ip addr add $HOST_IP/24 dev $VETH_HOST
ip link set $VETH_HOST up
ip netns exec $NS ip addr add $NS_IP/24 dev veth_ns
ip netns exec $NS ip link set veth_ns up
ip netns exec $NS ip link set lo up

if command -v firewall-cmd >/dev/null 2>&1; then
  # OpenSuse-specific
  firewall-cmd --zone=trusted --change-interface=$VETH_HOST > /dev/null 2>&1
fi

echo "[2] Launching tun2socks..."
# Socks server must accept packages from $HOST_IP
ip netns exec $NS $TUN2SOCKS_BIN -device tun0 -proxy socks5://$HOST_IP:$SOCKS_PORT &
TUN_PID=$!
sleep 1

echo "[3] Setting up routing..."
ip netns exec $NS ip link set tun0 up
ip netns exec $NS ip route add 0.0.0.0/1 dev tun0
ip netns exec $NS ip route add 128.0.0.0/1 dev tun0
mkdir -p /etc/netns/$NS
echo "nameserver 1.1.1.1" > /etc/netns/$NS/resolv.conf

echo "[4] Launching command from $REAL_USER: ${CMD[*]}"
ip netns exec $NS sudo -u $REAL_USER -E env \
  DISPLAY="$__DISP" \
  WAYLAND_DISPLAY="$__WAY" \
  XDG_RUNTIME_DIR="$__XDG" \
  XAUTHORITY="$__XAUTH" \
  DBUS_SESSION_BUS_ADDRESS="$__DBUS" \
  "${CMD[@]}"
